# Generated by Django 5.2.9 on 2026-01-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('key', models.CharField(help_text='Ej: MISION, VISION, QUIENES_SOMOS', max_length=60, unique=True, verbose_name='Clave')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Contenido')),
                ('icon', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ícono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bloque informativo',
                'verbose_name_plural': 'Bloques informativos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=160, verbose_name='Certificación')),
                ('issuer', models.CharField(blank=True, max_length=160, null=True, verbose_name='Entidad emisora')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('full_name', models.CharField(max_length=140, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=160, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('question', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=240, null=True, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Slide principal',
                'verbose_name_plural': 'Slides principales',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('key', models.CharField(max_length=60, unique=True, verbose_name='Clave')),
                ('label', models.CharField(max_length=120, verbose_name='Etiqueta')),
                ('value', models.CharField(max_length=40, verbose_name='Valor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('path', models.CharField(max_length=200, verbose_name='Ruta')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador')),
                ('country', models.CharField(blank=True, max_length=80, null=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ícono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('brand_name', models.CharField(default='Dorado Travel', max_length=120, verbose_name='Nombre de la marca')),
                ('hero_title', models.CharField(default='Explora la Selva Profunda', max_length=200, verbose_name='Título principal')),
                ('hero_subtitle', models.CharField(max_length=240, verbose_name='Subtítulo principal')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(max_length=40, verbose_name='Teléfono')),
                ('contact_address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='WhatsApp')),
                ('horario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario de atención')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('role', models.CharField(max_length=120, verbose_name='Cargo')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ubicación')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Calificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ícono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=260, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción completa')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='packages/covers/', verbose_name='Imagen principal')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por persona')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duración (días)')),
                ('difficulty', models.CharField(choices=[('FACIL', 'Fácil'), ('MODERADA', 'Moderada'), ('DIFICIL', 'Difícil')], default='MODERADA', max_length=12, verbose_name='Dificultad')),
                ('max_group', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. personas')),
                ('activities_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de actividades')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popular')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='turismo.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Paquete turístico',
                'verbose_name_plural': 'Paquetes turísticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('text', models.CharField(max_length=200, verbose_name='Incluye')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='turismo.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Incluye',
                'verbose_name_plural': 'Incluye',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('day', models.PositiveIntegerField(verbose_name='Día')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='turismo.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ['day', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('image', models.ImageField(upload_to='packages/photos/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='turismo.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Foto del paquete',
                'verbose_name_plural': 'Fotos del paquete',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('full_name', models.CharField(max_length=140, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Fecha de viaje')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Adultos')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Niños')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto total')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('public_code', models.CharField(help_text='Código para que el cliente consulte su reserva', max_length=16, unique=True, verbose_name='Código público')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='turismo.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
