# Generated by Django 5.2.9 on 2026-01-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nationality',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nacionalidad'),
        ),
    ]
