# Generated by Django 5.2.9 on 2026-01-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_reservation_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del cliente')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono')),
                ('nationality', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nacionalidad')),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PAGADO', 'Pagado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=12, verbose_name='Estado')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Fecha de viaje')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Adultos')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Niños')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='turismo.cart')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='turismo.package')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='turismo.reservation')),
            ],
            options={
                'verbose_name': 'Item de carrito',
                'verbose_name_plural': 'Items de carrito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('provider', models.CharField(default='SIMULADO', max_length=30, verbose_name='Proveedor')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('reference', models.CharField(max_length=60, unique=True, verbose_name='Referencia')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='turismo.cart')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
